#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.11.4
dpkg-maintscript-helper rm_conffile /etc/init/php8.2-fpm.conf 7.4.3-4\~ php8.2-fpm -- "$@"
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/php8.2-fpm" ] ; then
	chmod +x "/etc/init.d/php8.2-fpm" >/dev/null || true
fi
# End automatically added section
